name: CI - Backend Application

on:
  push:
    branches: [main]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10.5
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          cd $GITHUB_WORKSPACE/Backend/Services/Core.API/API/src
          apt-get update && apt-get upgrade && \ apt-get
            install -y python3 python-pip python3-dev python-dev wget &&
            update-alternatives --install /usr/bin/python python /usr/bin/python3 1 && \
            apt-get install build-essential libssl-dev libffi-dev python-dev 
          apt-get install wget libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev libsdl1.2-dev
            libsmpeg-dev python-numpy subversion libportmidi-dev ffmpeg libswscale-dev
            libavformat-dev libavcodec-dev libfreetype6-dev libsdl-image1.2-dev
            libsdl-mixer1.2-dev libsdl-ttf2.0-dev libsdl1.2-dev libsmpeg-dev python-numpy
            subversion libportmidi-dev ffmpeg libswscale-dev libavformat-dev
            libavcodec-dev libfreetype6-dev 
          apt-get install ffmpeg
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Lint with flake8
        run: |
          cd $GITHUB_WORKSPACE/Backend/Services/Core.API/API/src
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          
      # Run our unit tests using the test application
      - name: Run unit and integration tests
        run: |
          cd $GITHUB_WORKSPACE/Backend/Services/Core.API/API/src
          python3 -m pytest
